### ISSUE TITLE
Relay ReadTheDocs build failures to github

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/build.clusterhq.com#17]
I'm not sure if this is something that our buildbot should do, but it would be nice to have a service that received ReadTheDocs build failure webhooks and relayed those into the Github pull request build status message.
 * https://readthedocs.org/dashboard/flocker/notifications/

This might have prevented https://github.com/ClusterHQ/flocker/issues/620 

See: https://github.com/ClusterHQ/build.clusterhq.com/blob/master/flocker_bb/github.py for the current github status update code.

**Comment by exarkun** [comment]
We've stopped using RTD.
