### ISSUE TITLE
Automatically upload Python and RPM packages to archive.clusterhq.com

### ISSUE THREAD

**Issue by wallrj** [ClusterHQ/build.clusterhq.com#22]
If buildbot could automatically upload Python sdist and wheels and RPM packages to `archive.clusterhq.com` it would greatly simplify the release process.

We could also update the tutorial installation scripts in the "latest" documentation to download the "master" packages and then we'd be able to track how many times they'd been downloaded.

We could also update the Homebrew recipe to download the latest "master" package when the user used the `--HEAD` option. See: https://github.com/ClusterHQ/flocker/issues/678

It would also speed up the weekly releases. See https://github.com/ClusterHQ/flocker/pull/665

**Comment by exarkun** [comment]
We do this now.
